name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: Archerist
        reponame: archerist.github.io
        token: ${{ secrets.GITHUB_TOKEN }}
		cname: archerist.dev
	permissions:
		contents: write
		repository-projects: write
		packages: write